#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActionKind {
    TriggerLoop,
    RunEvalSuite,
    GradeTrace,
    MintCredential,
    WriteMemory,
    WriteCharter,
    RecordAdjustment,
    RunSecurityScan,
    ClassifyFinding,
    PlanRemediation,
    AcceptForgeSpec,
    RecordForgeStageTransition,
    RequestForgeDelegation,
    RequestForgeIntakePlan,
    RequestForgeBuild,
    ApproveForgeBuildPlan,
    RecordForgeWorkflowPlanProof,
    RecordDxrRunControl,
    RecordMarketplaceAct,
    DraftMarketplaceSkill,
    RatifyMarketplaceSkill,
    RecordCapabilityExecutionGrant,
    RevokeCapabilityExecutionGrant,
    RunCapabilityExecution,
    RefuseCapabilityExecution,
    ProposeHarnessPipeline,
    AdmitHarnessPipeline,
    MediateHarnessPipelineStage,
    RecordHarnessPipelineVerdict,
    RequestForgeWorkerAuthority,
    IngestProductSignal,
    ShapeProductBet,
    RequestProductHandoff,
    AuthorizeTalentSponsorChain,
    AuthorizeTalentWorkerLease,
    AuthorizeTalentBudget,
    AuthorizeTalentToolAllowlist,
    RequestWorkerSpawn,
    RecordWorkerHandoff,
    RetireWorker,
    RecordTalentAuthorization,
    CheckWorkerCredential,
    CheckWorkerSpawnPreflight,
    CheckForgeCiEvidencePreflight,
    PreflightForgeHumanRatification,
    PreflightForgeDeployment,
    CheckCharterObligation,
    AttestCharterEvidence,
    ReviewCharterException,
    AdmitHarnessRun,
    EmitHarnessPlan,
    RefuseHarnessWrite,
    MediateHarnessRead,
    DenyHarnessTool,
    SearchHarnessArtifact,
    ListHarnessArtifacts,
    MediateHarnessPatch,
    SelectHarnessProviderProfile,
    DenyHarnessProviderProfile,
    ApproveHarnessPlanHash,
    DenyHarnessExecution,
    ApplyHarnessPatch,
    ExecuteHarnessTest,
    AdmitHarnessWorkerScale,
    RecordDurableQueueEvent,
    DelegateHarnessWorker,
    RecordHarnessWorkerBuild,
    RecordHarnessWorkerHandoff,
    RetireHarnessWorker,
    ObserveHarnessCiEvidence,
    AssembleHarnessReviewPacket,
    RecordAutonomyEnvelope,
    RevokeAutonomyEnvelope,
    AmendAutonomyEnvelope,
    SweepExpiredAutonomyEnvelope,
    AssembleForgeOperatorDecisionPacket,
    RecordForgeHumanShipDecision,
    AssembleHarnessShipReadiness,
    RecordHarnessQualityGate,
    RecordHarnessFinalVerdict,
    ConsumeHarnessForgeReceipts,
    DenyHarnessForgeAction,
    RecordHarnessForgeVerdict,
    ConsumeHarnessTalentWorkerReceipts,
    DenyHarnessTalentWorkerAction,
    RecordHarnessTalentWorkerVerdict,
    AdmitHarnessExternalMachineRequest,
    DenyHarnessExternalMachineAdapter,
    ImportHarnessExternalMachineEvidence,
    RecordHarnessExternalMachineVerdict,
    IngestForgeFleetEvalResult,
    RecordForgeFleetEvalRunnerExecution,
    ScoreForgeFleetEvalResult,
    ApproveForgeFleetEvalLiveRun,
    AdmitForgeLongHorizonMission,
    RecordForgeLongHorizonMissionCheckpoint,
    ClassifyForgeWork,
    RecordForgePrHandoff,
    RecordForgeBuilderLoopTick,
    RecordForgeBuilderLoopRunAttachment,
    RecordForgeBuilderLoopCheckerAttachment,
    RecordForgeBuilderLoopFleetAttachment,
    RecordForgeBuilderLoopExternalTrialAttachment,
    AdmitTwinSessionDraft,
    AdmitTwinArtifact,
    DeclareTwinArtifactStorage,
    RecordTwinArtifactBlobStored,
    AuthorizeTwinArtifactDownload,
    ParseTwinArtifactWithLiteParse,
    ParseTwinArtifactContext,
    GroundTwinArtifactContext,
    CreateTwinArtifactPagesDraft,
    DeleteTwinArtifact,
    GenerateTwinOfficeArtifact,
    AuthorizeTwinOfficeArtifactDownload,
    RefuseTwinProviderCall,
    RefuseTwinProductionMemoryWrite,
    RefuseTwinToolExecution,
    PreflightTwinAgentMode,
    PreflightTwinHook,
    PreflightTwinSkill,
    PreflightTwinConnector,
    PreflightTwinAgentHandoff,
    PostMessageThreadMessage,
    RequestMessageAction,
    RecordMessageActionVerdict,
    RequestMessageFanout,
    RequestMessagePresence,
    PreflightMessageRealtimeCutover,
    RecordMessageDeliveryReplay,
    CheckMessageSubscriptionIsolation,
    RefuseMessageServiceRoleFanout,
    RecordMessageRelayObservation,
    PublishPagesDocument,
    ConsultAdvisor,
    RecordStudioDocumentRun,
    ClaimInstallOwner,
    ApproveModelTurnOn,
    ChooseSetupTrack,
    RecordFirstRunProfile,
    RecordActivationEvent,
    SavePagesEditDraft,
    RequestPagesApproval,
    RecordPagesApprovalDecision,
    RecordPagesContextSourceTrustDecision,
    PreflightPagesSearchIndexing,
    ComparePagesRevisionCitation,
    CheckPagesPublicationVisibility,
    RefusePagesEmbeddingProvider,
    PreflightAuthTenantPolicy,
    RequestAuthInvite,
    ApproveAuthUserAdmission,
    RecordAuthRoleAssignment,
    RecordMobileTrustEvent,
    RecordEvidenceCheckpoint,
    RecordEvidenceAnchor,
    RecordLearningEvidenceRequest,
    RecordLearningImplicitSignal,
    RecordLearningJudgmentDecision,
    RejectLearningCandidate,
    RequestLearningMemoryPromotion,
    ActivateLearningMemory,
    SupersedeLearningMemory,
    DraftFixtureGraduation,
    GrantLearningAdaptation,
    ApplyLearningAdaptation,
    SupersedeLearningAdaptation,
    RecordProductRatificationDecision,
    RecordProductBetDraft,
    RecordProductBetCondition,
    RecordProductBetConditionUpdate,
    RecordProductBetResolution,
    RecordWorkItemShape,
    RecordWorkItemMove,
    RecordForgeRunEvent,
    RecordForgeRunRefusal,
    RecordForgeOutcomeSignal,
    RecordForgeRunShipDecision,
    RecordForgeExecutionPosture,
    ConnectForgeRepo,
    IndexForgeRepo,
    RecordForgeRunControl,
    RecordFleetPlan,
    RecordChangelogEntry,
    IngestExternalItem,
    DeleteExternalItem,
    RecordForgeReviewPanel,
    RatifyFleetPlan,
    RecordFleetRunEvent,
    RecordTriageEntry,
    RecordTriageVerdict,
    RecordStrategyCondition,
    RecordStrategyConditionUpdate,
    RecordStrategyProposalResolution,
    RecordStrategyDirectionProposal,
    RecordStrategyDirectionRecord,
    RecordStrategyRatificationDecision,
    RecordAuthSessionActivation,
    RecordAuthSessionRevocation,
    RefuseAuthTenantSwitch,
    RefuseAuthRoleEscalation,
    RequestV1ReadShadowApproval,
    RecordV1ReadShadowApprovalDecision,
    RequestV1WriteMirrorApproval,
    RecordV1WriteMirrorApprovalDecision,
    AssembleLocalContext,
    RefuseCtxEmbeddingProvider,
    RecordBetaFeedback,
    RecordBetaEnrollment,
    RecordBetaTelemetry,
    RejectBetaTelemetry,
    RecordAppHealth,
    RejectAppHealth,
    RecordAppHealthSelfHealScan,
    RecordFeedbackAutonomyEvent,
    CreateMessageChannel,
    UpdateMessageChannel,
    AddMessageChannelMember,
    RemoveMessageChannelMember,
    RecordMessageBridgePost,
    EconomicSpend { amount_cents: u32 },
}

impl ActionKind {
    pub fn name(&self) -> &'static str {
        match self {
            Self::TriggerLoop => "trigger_loop",
            Self::RunEvalSuite => "run_eval_suite",
            Self::GradeTrace => "grade_trace",
            Self::MintCredential => "mint_credential",
            Self::WriteMemory => "write_memory",
            Self::WriteCharter => "write_charter",
            Self::RecordAdjustment => "record_adjustment",
            Self::RunSecurityScan => "run_security_scan",
            Self::ClassifyFinding => "classify_finding",
            Self::PlanRemediation => "plan_remediation",
            Self::AcceptForgeSpec => "accept_forge_spec",
            Self::RecordForgeStageTransition => "record_forge_stage_transition",
            Self::RequestForgeDelegation => "request_forge_delegation",
            Self::RequestForgeIntakePlan => "request_forge_intake_plan",
            Self::RequestForgeBuild => "request_forge_build",
            Self::ApproveForgeBuildPlan => "approve_forge_build_plan",
            Self::RecordForgeWorkflowPlanProof => "record_forge_workflow_plan_proof",
            Self::RecordDxrRunControl => "record_dxr_run_control",
            Self::RecordMarketplaceAct => "record_marketplace_act",
            Self::DraftMarketplaceSkill => "draft_marketplace_skill",
            Self::RatifyMarketplaceSkill => "ratify_marketplace_skill",
            Self::RecordCapabilityExecutionGrant => "record_capability_execution_grant",
            Self::RevokeCapabilityExecutionGrant => "revoke_capability_execution_grant",
            Self::RunCapabilityExecution => "run_capability_execution",
            Self::RefuseCapabilityExecution => "refuse_capability_execution",
            Self::ProposeHarnessPipeline => "propose_harness_pipeline",
            Self::AdmitHarnessPipeline => "admit_harness_pipeline",
            Self::MediateHarnessPipelineStage => "mediate_harness_pipeline_stage",
            Self::RecordHarnessPipelineVerdict => "record_harness_pipeline_verdict",
            Self::RequestForgeWorkerAuthority => "request_forge_worker_authority",
            Self::IngestProductSignal => "ingest_product_signal",
            Self::ShapeProductBet => "shape_product_bet",
            Self::RequestProductHandoff => "request_product_handoff",
            Self::AuthorizeTalentSponsorChain => "authorize_talent_sponsor_chain",
            Self::AuthorizeTalentWorkerLease => "authorize_talent_worker_lease",
            Self::AuthorizeTalentBudget => "authorize_talent_budget",
            Self::AuthorizeTalentToolAllowlist => "authorize_talent_tool_allowlist",
            Self::RecordTalentAuthorization => "record_talent_authorization",
            Self::CheckWorkerCredential => "check_worker_credential",
            Self::CheckWorkerSpawnPreflight => "check_worker_spawn_preflight",
            Self::CheckForgeCiEvidencePreflight => "check_forge_ci_evidence_preflight",
            Self::PreflightForgeHumanRatification => "preflight_forge_human_ratification",
            Self::PreflightForgeDeployment => "preflight_forge_deployment",
            Self::RequestWorkerSpawn => "request_worker_spawn",
            Self::RecordWorkerHandoff => "record_worker_handoff",
            Self::RetireWorker => "retire_worker",
            Self::CheckCharterObligation => "check_charter_obligation",
            Self::AttestCharterEvidence => "attest_charter_evidence",
            Self::ReviewCharterException => "review_charter_exception",
            Self::AdmitHarnessRun => "admit_harness_run",
            Self::EmitHarnessPlan => "emit_harness_plan",
            Self::RefuseHarnessWrite => "refuse_harness_write",
            Self::MediateHarnessRead => "mediate_harness_read",
            Self::DenyHarnessTool => "deny_harness_tool",
            Self::SearchHarnessArtifact => "search_harness_artifact",
            Self::ListHarnessArtifacts => "list_harness_artifacts",
            Self::MediateHarnessPatch => "mediate_harness_patch",
            Self::SelectHarnessProviderProfile => "select_harness_provider_profile",
            Self::DenyHarnessProviderProfile => "deny_harness_provider_profile",
            Self::ApproveHarnessPlanHash => "approve_harness_plan_hash",
            Self::DenyHarnessExecution => "deny_harness_execution",
            Self::ApplyHarnessPatch => "apply_harness_patch",
            Self::ExecuteHarnessTest => "execute_harness_test",
            Self::AdmitHarnessWorkerScale => "admit_harness_worker_scale",
            Self::RecordDurableQueueEvent => "record_durable_queue_event",
            Self::DelegateHarnessWorker => "delegate_harness_worker",
            Self::RecordHarnessWorkerBuild => "record_harness_worker_build",
            Self::RecordHarnessWorkerHandoff => "record_harness_worker_handoff",
            Self::RetireHarnessWorker => "retire_harness_worker",
            Self::ObserveHarnessCiEvidence => "observe_harness_ci_evidence",
            Self::AssembleHarnessReviewPacket => "assemble_harness_review_packet",
            Self::RecordAutonomyEnvelope => "record_autonomy_envelope",
            Self::RevokeAutonomyEnvelope => "revoke_autonomy_envelope",
            Self::AmendAutonomyEnvelope => "amend_autonomy_envelope",
            Self::SweepExpiredAutonomyEnvelope => "sweep_expired_autonomy_envelope",
            Self::AssembleForgeOperatorDecisionPacket => "assemble_forge_operator_decision_packet",
            Self::RecordForgeHumanShipDecision => "record_forge_human_ship_decision",
            Self::AssembleHarnessShipReadiness => "assemble_harness_ship_readiness",
            Self::RecordHarnessQualityGate => "record_harness_quality_gate",
            Self::RecordHarnessFinalVerdict => "record_harness_final_verdict",
            Self::ConsumeHarnessForgeReceipts => "consume_harness_forge_receipts",
            Self::DenyHarnessForgeAction => "deny_harness_forge_action",
            Self::RecordHarnessForgeVerdict => "record_harness_forge_verdict",
            Self::ConsumeHarnessTalentWorkerReceipts => "consume_harness_talent_worker_receipts",
            Self::DenyHarnessTalentWorkerAction => "deny_harness_talent_worker_action",
            Self::RecordHarnessTalentWorkerVerdict => "record_harness_talent_worker_verdict",
            Self::AdmitHarnessExternalMachineRequest => "admit_harness_external_machine_request",
            Self::DenyHarnessExternalMachineAdapter => "deny_harness_external_machine_adapter",
            Self::ImportHarnessExternalMachineEvidence => {
                "import_harness_external_machine_evidence"
            }
            Self::RecordHarnessExternalMachineVerdict => "record_harness_external_machine_verdict",
            Self::IngestForgeFleetEvalResult => "ingest_forge_fleet_eval_result",
            Self::RecordForgeFleetEvalRunnerExecution => "record_forge_fleet_eval_runner_execution",
            Self::ScoreForgeFleetEvalResult => "score_forge_fleet_eval_result",
            Self::ApproveForgeFleetEvalLiveRun => "approve_forge_fleet_eval_live_run",
            Self::AdmitForgeLongHorizonMission => "admit_forge_long_horizon_mission",
            Self::RecordForgeLongHorizonMissionCheckpoint => {
                "record_forge_long_horizon_mission_checkpoint"
            }
            Self::ClassifyForgeWork => "classify_forge_work",
            Self::RecordForgePrHandoff => "record_forge_pr_handoff",
            Self::RecordForgeBuilderLoopTick => "record_forge_builder_loop_tick",
            Self::RecordForgeBuilderLoopRunAttachment => "record_forge_builder_loop_run_attachment",
            Self::RecordForgeBuilderLoopCheckerAttachment => {
                "record_forge_builder_loop_checker_attachment"
            }
            Self::RecordForgeBuilderLoopFleetAttachment => {
                "record_forge_builder_loop_fleet_attachment"
            }
            Self::RecordForgeBuilderLoopExternalTrialAttachment => {
                "record_forge_builder_loop_external_trial_attachment"
            }
            Self::AdmitTwinSessionDraft => "admit_twin_session_draft",
            Self::AdmitTwinArtifact => "admit_twin_artifact",
            Self::DeclareTwinArtifactStorage => "declare_twin_artifact_storage",
            Self::RecordTwinArtifactBlobStored => "record_twin_artifact_blob_stored",
            Self::AuthorizeTwinArtifactDownload => "authorize_twin_artifact_download",
            Self::ParseTwinArtifactWithLiteParse => "parse_twin_artifact_with_liteparse",
            Self::ParseTwinArtifactContext => "parse_twin_artifact_context",
            Self::GroundTwinArtifactContext => "ground_twin_artifact_context",
            Self::CreateTwinArtifactPagesDraft => "create_twin_artifact_pages_draft",
            Self::DeleteTwinArtifact => "delete_twin_artifact",
            Self::GenerateTwinOfficeArtifact => "generate_twin_office_artifact",
            Self::AuthorizeTwinOfficeArtifactDownload => "authorize_twin_office_artifact_download",
            Self::RefuseTwinProviderCall => "refuse_twin_provider_call",
            Self::RefuseTwinProductionMemoryWrite => "refuse_twin_production_memory_write",
            Self::RefuseTwinToolExecution => "refuse_twin_tool_execution",
            Self::PreflightTwinAgentMode => "preflight_twin_agent_mode",
            Self::PreflightTwinHook => "preflight_twin_hook",
            Self::PreflightTwinSkill => "preflight_twin_skill",
            Self::PreflightTwinConnector => "preflight_twin_connector",
            Self::PreflightTwinAgentHandoff => "preflight_twin_agent_handoff",
            Self::PostMessageThreadMessage => "post_message_thread_message",
            Self::RequestMessageAction => "request_message_action",
            Self::RecordMessageActionVerdict => "record_message_action_verdict",
            Self::RequestMessageFanout => "request_message_fanout",
            Self::RequestMessagePresence => "request_message_presence",
            Self::PreflightMessageRealtimeCutover => "preflight_message_realtime_cutover",
            Self::RecordMessageDeliveryReplay => "record_message_delivery_replay",
            Self::CheckMessageSubscriptionIsolation => "check_message_subscription_isolation",
            Self::RefuseMessageServiceRoleFanout => "refuse_message_service_role_fanout",
            Self::RecordMessageRelayObservation => "record_message_relay_observation",
            Self::PublishPagesDocument => "publish_pages_document",
            Self::ConsultAdvisor => "consult_advisor",
            Self::RecordStudioDocumentRun => "record_studio_document_run",
            Self::ClaimInstallOwner => "claim_install_owner",
            Self::ApproveModelTurnOn => "approve_model_turn_on",
            Self::ChooseSetupTrack => "choose_setup_track",
            Self::RecordFirstRunProfile => "record_first_run_profile",
            Self::RecordActivationEvent => "record_activation_event",
            Self::SavePagesEditDraft => "save_pages_edit_draft",
            Self::RequestPagesApproval => "request_pages_approval",
            Self::RecordPagesApprovalDecision => "record_pages_approval_decision",
            Self::RecordPagesContextSourceTrustDecision => {
                "record_pages_context_source_trust_decision"
            }
            Self::PreflightPagesSearchIndexing => "preflight_pages_search_indexing",
            Self::ComparePagesRevisionCitation => "compare_pages_revision_citation",
            Self::CheckPagesPublicationVisibility => "check_pages_publication_visibility",
            Self::RefusePagesEmbeddingProvider => "refuse_pages_embedding_provider",
            Self::PreflightAuthTenantPolicy => "preflight_auth_tenant_policy",
            Self::RequestAuthInvite => "request_auth_invite",
            Self::ApproveAuthUserAdmission => "approve_auth_user_admission",
            Self::RecordAuthRoleAssignment => "record_auth_role_assignment",
            Self::RecordMobileTrustEvent => "record_mobile_trust_event",
            Self::RecordEvidenceCheckpoint => "record_evidence_checkpoint",
            Self::RecordEvidenceAnchor => "record_evidence_anchor",
            Self::RecordLearningEvidenceRequest => "record_learning_evidence_request",
            Self::RecordLearningImplicitSignal => "record_learning_implicit_signal",
            Self::RecordLearningJudgmentDecision => "record_learning_judgment_decision",
            Self::RejectLearningCandidate => "reject_learning_candidate",
            Self::RequestLearningMemoryPromotion => "request_learning_memory_promotion",
            Self::ActivateLearningMemory => "activate_learning_memory",
            Self::SupersedeLearningMemory => "supersede_learning_memory",
            Self::DraftFixtureGraduation => "draft_fixture_graduation",
            Self::GrantLearningAdaptation => "grant_learning_adaptation",
            Self::ApplyLearningAdaptation => "apply_learning_adaptation",
            Self::SupersedeLearningAdaptation => "supersede_learning_adaptation",
            Self::RecordProductRatificationDecision => "record_product_ratification_decision",
            Self::RecordProductBetDraft => "record_product_bet_draft",
            Self::RecordProductBetCondition => "record_product_bet_condition",
            Self::RecordProductBetConditionUpdate => "record_product_bet_condition_update",
            Self::RecordProductBetResolution => "record_product_bet_resolution",
            Self::RecordWorkItemShape => "record_work_item_shape",
            Self::RecordWorkItemMove => "record_work_item_move",
            Self::RecordForgeRunEvent => "record_forge_run_event",
            Self::RecordForgeRunRefusal => "record_forge_run_refusal",
            Self::RecordForgeOutcomeSignal => "record_forge_outcome_signal",
            Self::RecordForgeRunShipDecision => "record_forge_run_ship_decision",
            Self::RecordForgeExecutionPosture => "record_forge_execution_posture",
            Self::ConnectForgeRepo => "connect_forge_repo",
            Self::IndexForgeRepo => "index_forge_repo",
            Self::RecordForgeRunControl => "record_forge_run_control",
            Self::RecordFleetPlan => "record_fleet_plan",
            Self::RecordChangelogEntry => "record_changelog_entry",
            Self::IngestExternalItem => "ingest_external_item",
            Self::DeleteExternalItem => "delete_external_item",
            Self::RecordForgeReviewPanel => "record_forge_review_panel",
            Self::RatifyFleetPlan => "ratify_fleet_plan",
            Self::RecordFleetRunEvent => "record_fleet_run_event",
            Self::RecordTriageEntry => "record_triage_entry",
            Self::RecordTriageVerdict => "record_triage_verdict",
            Self::RecordStrategyCondition => "record_strategy_condition",
            Self::RecordStrategyConditionUpdate => "record_strategy_condition_update",
            Self::RecordStrategyProposalResolution => "record_strategy_proposal_resolution",
            Self::RecordStrategyDirectionProposal => "record_strategy_direction_proposal",
            Self::RecordStrategyDirectionRecord => "record_strategy_direction_record",
            Self::RecordStrategyRatificationDecision => "record_strategy_ratification_decision",
            Self::RecordAuthSessionActivation => "record_auth_session_activation",
            Self::RecordAuthSessionRevocation => "record_auth_session_revocation",
            Self::RefuseAuthTenantSwitch => "refuse_auth_tenant_switch",
            Self::RefuseAuthRoleEscalation => "refuse_auth_role_escalation",
            Self::RequestV1ReadShadowApproval => "request_v1_read_shadow_approval",
            Self::RecordV1ReadShadowApprovalDecision => "record_v1_read_shadow_approval_decision",
            Self::RequestV1WriteMirrorApproval => "request_v1_write_mirror_approval",
            Self::RecordV1WriteMirrorApprovalDecision => "record_v1_write_mirror_approval_decision",
            Self::AssembleLocalContext => "assemble_local_context",
            Self::RefuseCtxEmbeddingProvider => "refuse_ctx_embedding_provider",
            Self::RecordBetaFeedback => "record_beta_feedback",
            Self::RecordBetaEnrollment => "record_beta_enrollment",
            Self::RecordBetaTelemetry => "record_beta_telemetry",
            Self::RejectBetaTelemetry => "reject_beta_telemetry",
            Self::RecordAppHealth => "record_app_health",
            Self::RejectAppHealth => "reject_app_health",
            Self::RecordAppHealthSelfHealScan => "record_app_health_self_heal_scan",
            Self::RecordFeedbackAutonomyEvent => "record_feedback_autonomy_event",
            Self::CreateMessageChannel => "create_message_channel",
            Self::UpdateMessageChannel => "update_message_channel",
            Self::AddMessageChannelMember => "add_message_channel_member",
            Self::RemoveMessageChannelMember => "remove_message_channel_member",
            Self::RecordMessageBridgePost => "record_message_bridge_post",
            Self::EconomicSpend { .. } => "economic_spend",
        }
    }

    pub fn is_economic(&self) -> bool {
        matches!(self, Self::EconomicSpend { .. })
    }
}
