use crate::*;

pub const TWIN_OFFICE_NATIVE_PACK_ID: &str = "mdx.office.native.v0";
pub const TWIN_OFFICE_NATIVE_PACK_VERSION: &str = "0.1.0";
pub const TWIN_OFFICE_GENERATION_POLICY: &str = "local_twin_office_generation_v1";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TwinOfficeGeneratedArtifactRequest<'a> {
    pub tenant_id: &'a str,
    pub actor_id: &'a str,
    pub artifact_id: &'a str,
    pub artifact_kind: &'a str,
    pub title: &'a str,
    pub output_ref: &'a str,
    pub output_hash: &'a str,
    pub output_bytes: usize,
    pub content_type: &'a str,
    pub engine_id: &'a str,
    pub validation_status: &'a str,
    pub generation_spec_hash: &'a str,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TwinOfficeGeneratedArtifactReport {
    pub status: &'static str,
    pub route: &'static str,
    pub runtime_route: &'static str,
    pub capability_pack_id: &'static str,
    pub capability_pack_version: &'static str,
    pub artifact_id: String,
    pub artifact_kind: String,
    pub title: String,
    pub output_ref: String,
    pub output_hash: String,
    pub output_bytes: usize,
    pub content_type: String,
    pub engine_id: String,
    pub validation_status: String,
    pub generation_spec_hash: String,
    pub office_generation_receipt_id: String,
    pub policy_decision_id: String,
    pub download_allowed: bool,
    pub raw_private_content_recorded: bool,
    pub provider_call_allowed: bool,
    pub frontier_raw_content_allowed: bool,
    pub memory_write_performed: bool,
    pub production_write_allowed: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TwinOfficeDownloadRequest<'a> {
    pub tenant_id: &'a str,
    pub actor_id: &'a str,
    pub artifact_id: &'a str,
    pub artifact_kind: &'a str,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TwinOfficeDownloadReport {
    pub status: &'static str,
    pub route: &'static str,
    pub runtime_route: &'static str,
    pub artifact_id: String,
    pub artifact_kind: String,
    pub output_ref: String,
    pub output_hash: String,
    pub output_bytes: usize,
    pub content_type: String,
    pub office_generation_receipt_id: String,
    pub office_download_receipt_id: String,
    pub policy_decision_id: String,
    pub download_allowed: bool,
    pub owner_authorized: bool,
    pub raw_private_content_recorded: bool,
    pub provider_call_allowed: bool,
    pub frontier_raw_content_allowed: bool,
    pub memory_write_performed: bool,
    pub production_write_allowed: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TwinOfficeCapabilityError {
    Missing(&'static str),
    UnsupportedArtifactKind(String),
    InvalidOutput(String),
    ActorAdmission(String),
}

impl TwinOfficeCapabilityError {
    pub fn message(&self) -> String {
        match self {
            Self::Missing(field) => format!("missing twin office capability field: {field}"),
            Self::UnsupportedArtifactKind(kind) => {
                format!("unsupported twin office artifact kind: {kind}")
            }
            Self::InvalidOutput(detail) => format!("invalid twin office output: {detail}"),
            Self::ActorAdmission(detail) => format!("actor admission failed: {detail}"),
        }
    }
}

impl MdxKernel {
    pub fn record_twin_office_generated_artifact_local(
        &mut self,
        request: TwinOfficeGeneratedArtifactRequest<'_>,
    ) -> Result<TwinOfficeGeneratedArtifactReport, TwinOfficeCapabilityError> {
        for (field, value) in [
            ("tenant_id", request.tenant_id),
            ("actor_id", request.actor_id),
            ("artifact_id", request.artifact_id),
            ("artifact_kind", request.artifact_kind),
            ("title", request.title),
            ("output_ref", request.output_ref),
            ("output_hash", request.output_hash),
            ("content_type", request.content_type),
            ("engine_id", request.engine_id),
            ("validation_status", request.validation_status),
            ("generation_spec_hash", request.generation_spec_hash),
        ] {
            if value.trim().is_empty() {
                return Err(TwinOfficeCapabilityError::Missing(field));
            }
        }
        if !["docx", "xlsx", "pptx"].contains(&request.artifact_kind) {
            return Err(TwinOfficeCapabilityError::UnsupportedArtifactKind(
                request.artifact_kind.to_string(),
            ));
        }
        if request.output_bytes == 0 {
            return Err(TwinOfficeCapabilityError::InvalidOutput(
                "generated bytes must be non-empty".to_string(),
            ));
        }
        if request.validation_status != "OPENXML_PACKAGE_BYTES_PRESENT" {
            return Err(TwinOfficeCapabilityError::InvalidOutput(
                request.validation_status.to_string(),
            ));
        }

        let actor_admission = admit_local_route_actor(
            request.tenant_id,
            request.actor_id,
            "operator",
            "/twin/office/generated-artifacts.json",
            "twin.office.generated_artifact.created",
            request.artifact_id,
        )
        .map_err(|error| TwinOfficeCapabilityError::ActorAdmission(error.message()))?;

        let correlation = CorrelationIds {
            tenant_id: TenantId::new(request.tenant_id),
            trace_id: TraceId::new(self.ids.next("trace")),
            actor_id: ActorId::new(request.actor_id),
            loop_id: LoopId::new("twin_office_generation"),
            workflow_id: WorkflowId::new(self.ids.next("workflow")),
        };
        let run_id = self.ids.next("run");
        self.storage.push_loop_run(LoopRun {
            run_id: run_id.clone(),
            loop_id: correlation.loop_id.clone(),
            agent_id: correlation.actor_id.clone(),
            workflow_id: correlation.workflow_id.clone(),
            status: "RUNNING".to_string(),
        });

        let decision =
            self.decide_with_receipt(&correlation, ActionKind::GenerateTwinOfficeArtifact);
        let output_bytes = request.output_bytes.to_string();
        let receipt = self.transition_receipt(
            &run_id,
            "GENERATE_TWIN_OFFICE_ARTIFACT",
            &correlation,
            &decision,
            "twin.office.generated_artifact.created",
            payload(&[
                ("artifact_id", request.artifact_id),
                ("artifact_kind", request.artifact_kind),
                ("title_hash", &hex(&sha256(request.title.as_bytes()))),
                ("output_ref", request.output_ref),
                ("output_hash", request.output_hash),
                ("output_bytes", &output_bytes),
                ("content_type", request.content_type),
                ("capability_pack_id", TWIN_OFFICE_NATIVE_PACK_ID),
                ("capability_pack_version", TWIN_OFFICE_NATIVE_PACK_VERSION),
                ("generation_policy", TWIN_OFFICE_GENERATION_POLICY),
                ("engine_id", request.engine_id),
                ("validation_status", request.validation_status),
                ("generation_spec_hash", request.generation_spec_hash),
                ("download_allowed", "true"),
                ("source_intake_surface", "twin"),
                ("source_trust_state", "generated_output"),
                ("trusted_context_state", "not_company_context_until_review"),
                ("raw_private_content_recorded", "false"),
                ("raw_output_recorded", "false"),
                ("provider_call_allowed", "false"),
                ("frontier_raw_content_allowed", "false"),
                ("memory_write_performed", "false"),
                ("production_write_allowed", "false"),
                ("actor_admission_status", actor_admission.status),
                (
                    "actor_admission_policy_decision_id",
                    &actor_admission.policy_decision_id,
                ),
            ]),
        );

        if let Some(run) = self
            .storage
            .loop_runs_mut()
            .iter_mut()
            .find(|run| run.run_id == run_id)
        {
            run.status = "TWIN_OFFICE_GENERATED_ARTIFACT_CREATED_LOCAL".to_string();
        }

        Ok(TwinOfficeGeneratedArtifactReport {
            status: "TWIN_OFFICE_GENERATED_ARTIFACT_CREATED_LOCAL",
            route: "/twin/office/generated-artifacts.json",
            runtime_route: "/twin/office-capability-runtime.json",
            capability_pack_id: TWIN_OFFICE_NATIVE_PACK_ID,
            capability_pack_version: TWIN_OFFICE_NATIVE_PACK_VERSION,
            artifact_id: request.artifact_id.to_string(),
            artifact_kind: request.artifact_kind.to_string(),
            title: request.title.to_string(),
            output_ref: request.output_ref.to_string(),
            output_hash: request.output_hash.to_string(),
            output_bytes: request.output_bytes,
            content_type: request.content_type.to_string(),
            engine_id: request.engine_id.to_string(),
            validation_status: request.validation_status.to_string(),
            generation_spec_hash: request.generation_spec_hash.to_string(),
            office_generation_receipt_id: receipt.receipt_id,
            policy_decision_id: decision.policy_decision_id,
            download_allowed: true,
            raw_private_content_recorded: false,
            provider_call_allowed: false,
            frontier_raw_content_allowed: false,
            memory_write_performed: false,
            production_write_allowed: false,
        })
    }

    pub fn authorize_twin_office_download_local(
        &mut self,
        request: TwinOfficeDownloadRequest<'_>,
    ) -> Result<TwinOfficeDownloadReport, TwinOfficeCapabilityError> {
        for (field, value) in [
            ("tenant_id", request.tenant_id),
            ("actor_id", request.actor_id),
            ("artifact_id", request.artifact_id),
            ("artifact_kind", request.artifact_kind),
        ] {
            if value.trim().is_empty() {
                return Err(TwinOfficeCapabilityError::Missing(field));
            }
        }
        let generation = self
            .ledger()
            .entries()
            .iter()
            .rev()
            .find(|receipt| {
                receipt.kind == "twin.office.generated_artifact.created"
                    && receipt.payload.get("artifact_id").map(String::as_str)
                        == Some(request.artifact_id)
                    && receipt.payload.get("artifact_kind").map(String::as_str)
                        == Some(request.artifact_kind)
            })
            .map(|receipt| {
                (
                    receipt.receipt_id.clone(),
                    receipt
                        .payload
                        .get("output_ref")
                        .cloned()
                        .unwrap_or_default(),
                    receipt
                        .payload
                        .get("output_hash")
                        .cloned()
                        .unwrap_or_default(),
                    receipt
                        .payload
                        .get("output_bytes")
                        .and_then(|value| value.parse::<usize>().ok())
                        .unwrap_or_default(),
                    receipt
                        .payload
                        .get("content_type")
                        .cloned()
                        .unwrap_or_default(),
                )
            })
            .ok_or_else(|| {
                TwinOfficeCapabilityError::InvalidOutput(format!(
                    "unknown generated Office artifact {}",
                    request.artifact_id
                ))
            })?;
        let (office_generation_receipt_id, output_ref, output_hash, output_bytes, content_type) =
            generation;

        let actor_admission = admit_local_route_actor(
            request.tenant_id,
            request.actor_id,
            "operator",
            "/twin/office/downloads.json",
            "twin.office.download.authorized",
            request.artifact_id,
        )
        .map_err(|error| TwinOfficeCapabilityError::ActorAdmission(error.message()))?;

        let correlation = CorrelationIds {
            tenant_id: TenantId::new(request.tenant_id),
            trace_id: TraceId::new(self.ids.next("trace")),
            actor_id: ActorId::new(request.actor_id),
            loop_id: LoopId::new("twin_office_download"),
            workflow_id: WorkflowId::new(self.ids.next("workflow")),
        };
        let run_id = self.ids.next("run");
        self.storage.push_loop_run(LoopRun {
            run_id: run_id.clone(),
            loop_id: correlation.loop_id.clone(),
            agent_id: correlation.actor_id.clone(),
            workflow_id: correlation.workflow_id.clone(),
            status: "RUNNING".to_string(),
        });
        let decision = self.decide_with_receipt(
            &correlation,
            ActionKind::AuthorizeTwinOfficeArtifactDownload,
        );
        let output_bytes_text = output_bytes.to_string();
        let receipt = self.transition_receipt(
            &run_id,
            "AUTHORIZE_TWIN_OFFICE_DOWNLOAD",
            &correlation,
            &decision,
            "twin.office.download.authorized",
            payload(&[
                ("artifact_id", request.artifact_id),
                ("artifact_kind", request.artifact_kind),
                (
                    "office_generation_receipt_id",
                    &office_generation_receipt_id,
                ),
                ("output_ref", &output_ref),
                ("output_hash", &output_hash),
                ("output_bytes", &output_bytes_text),
                ("content_type", &content_type),
                ("download_allowed", "true"),
                ("owner_authorized", "true"),
                ("download_body_recorded", "false"),
                ("raw_private_content_recorded", "false"),
                ("provider_call_allowed", "false"),
                ("frontier_raw_content_allowed", "false"),
                ("memory_write_performed", "false"),
                ("production_write_allowed", "false"),
                ("actor_admission_status", actor_admission.status),
                (
                    "actor_admission_policy_decision_id",
                    &actor_admission.policy_decision_id,
                ),
            ]),
        );
        if let Some(run) = self
            .storage
            .loop_runs_mut()
            .iter_mut()
            .find(|run| run.run_id == run_id)
        {
            run.status = "TWIN_OFFICE_DOWNLOAD_READY_LOCAL".to_string();
        }
        Ok(TwinOfficeDownloadReport {
            status: "TWIN_OFFICE_DOWNLOAD_READY_LOCAL",
            route: "/twin/office/downloads.json",
            runtime_route: "/twin/office-capability-runtime.json",
            artifact_id: request.artifact_id.to_string(),
            artifact_kind: request.artifact_kind.to_string(),
            output_ref,
            output_hash,
            output_bytes,
            content_type,
            office_generation_receipt_id,
            office_download_receipt_id: receipt.receipt_id,
            policy_decision_id: decision.policy_decision_id,
            download_allowed: true,
            owner_authorized: true,
            raw_private_content_recorded: false,
            provider_call_allowed: false,
            frontier_raw_content_allowed: false,
            memory_write_performed: false,
            production_write_allowed: false,
        })
    }
}

impl TwinOfficeGeneratedArtifactReport {
    pub fn render_post_json(&self) -> String {
        format!(
            r#"{{"name":"mdx-twin-office-generated-artifact-local-post","status":{},"auth_session_required":true,"auth_session_route":"/local/auth-session.json","route":{},"runtime_route":{},"capability_pack_id":{},"capability_pack_version":{},"artifact_id":{},"artifact_kind":{},"title":{},"output_ref":{},"output_hash":{},"output_bytes":{},"content_type":{},"engine_id":{},"validation_status":{},"generation_spec_hash":{},"office_generation_receipt_id":{},"policy_decision_id":{},"download_allowed":{},"raw_private_content_recorded":{},"provider_call_allowed":{},"frontier_raw_content_allowed":{},"memory_write_performed":{},"production_write_allowed":{}}}"#,
            json_string_literal(self.status),
            json_string_literal(self.route),
            json_string_literal(self.runtime_route),
            json_string_literal(self.capability_pack_id),
            json_string_literal(self.capability_pack_version),
            json_string_literal(&self.artifact_id),
            json_string_literal(&self.artifact_kind),
            json_string_literal(&self.title),
            json_string_literal(&self.output_ref),
            json_string_literal(&self.output_hash),
            self.output_bytes,
            json_string_literal(&self.content_type),
            json_string_literal(&self.engine_id),
            json_string_literal(&self.validation_status),
            json_string_literal(&self.generation_spec_hash),
            json_string_literal(&self.office_generation_receipt_id),
            json_string_literal(&self.policy_decision_id),
            self.download_allowed,
            self.raw_private_content_recorded,
            self.provider_call_allowed,
            self.frontier_raw_content_allowed,
            self.memory_write_performed,
            self.production_write_allowed
        )
    }
}

impl TwinOfficeDownloadReport {
    pub fn render_download_json(&self, output_base64: &str) -> String {
        format!(
            r#"{{"name":"mdx-twin-office-download-local-post","status":{},"auth_session_required":true,"auth_session_route":"/local/auth-session.json","route":{},"runtime_route":{},"artifact_id":{},"artifact_kind":{},"output_ref":{},"output_hash":{},"output_bytes":{},"content_type":{},"office_generation_receipt_id":{},"office_download_receipt_id":{},"policy_decision_id":{},"download_allowed":{},"owner_authorized":{},"output_base64":{},"raw_private_content_recorded":{},"provider_call_allowed":{},"frontier_raw_content_allowed":{},"memory_write_performed":{},"production_write_allowed":{}}}"#,
            json_string_literal(self.status),
            json_string_literal(self.route),
            json_string_literal(self.runtime_route),
            json_string_literal(&self.artifact_id),
            json_string_literal(&self.artifact_kind),
            json_string_literal(&self.output_ref),
            json_string_literal(&self.output_hash),
            self.output_bytes,
            json_string_literal(&self.content_type),
            json_string_literal(&self.office_generation_receipt_id),
            json_string_literal(&self.office_download_receipt_id),
            json_string_literal(&self.policy_decision_id),
            self.download_allowed,
            self.owner_authorized,
            json_string_literal(output_base64),
            self.raw_private_content_recorded,
            self.provider_call_allowed,
            self.frontier_raw_content_allowed,
            self.memory_write_performed,
            self.production_write_allowed
        )
    }
}
