#!/usr/bin/env bash
set -euo pipefail

app_dir="apps/mdx-operator-macos"
swift_cache_root="${PWD}/.mdx-local/swiftpm"
mkdir -p "$swift_cache_root/home" "$swift_cache_root/clang-module-cache" "$swift_cache_root/swiftpm-cache"
export HOME="$swift_cache_root/home"
export XDG_CACHE_HOME="$swift_cache_root"
export CLANG_MODULE_CACHE_PATH="$swift_cache_root/clang-module-cache"
export SWIFTPM_CACHE_PATH="$swift_cache_root/swiftpm-cache"

test -f "$app_dir/Package.swift"
test -f "$app_dir/Sources/MDxOperator/App/MDxOperatorApp.swift"
test -f "$app_dir/Sources/MDxOperator/Views/ContentView.swift"
test -f "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
test -f "$app_dir/Sources/MDxOperator/Services/MacUpdaterController.swift"
test -f "$app_dir/Sources/MDxOperator/Stores/OperatorStore.swift"
test -f "$app_dir/Sources/MDxOperator/Models/BrowserReviewModels.swift"
test -f "$app_dir/Sources/MDxOperator/Views/BrowserPreviewView.swift"
test -f "$app_dir/Sources/MDxOperator/Views/MemoryView.swift"
test -x "$app_dir/script/build_and_run.sh"
test -x "$app_dir/script/package_release.sh"
test -x "$app_dir/script/package_dmg.sh"
test -f ".codex/environments/environment.toml"

grep -q 'name: "MDxWorkbench"' "$app_dir/Package.swift"
grep -q 'sparkle-project/Sparkle.git", exact: "2.9.4"' "$app_dir/Package.swift"
grep -q 'product(name: "Sparkle"' "$app_dir/Package.swift"
grep -q 'Authorization.*Bearer' "$app_dir/Sources/MDxOperator/Services/MacUpdaterController.swift"
grep -q 'checkForUpdateInformation' "$app_dir/Sources/MDxOperator/Services/MacUpdaterController.swift"
grep -q 'checkForUpdates(nil)' "$app_dir/Sources/MDxOperator/Services/MacUpdaterController.swift"
grep -q 'download/macos/appcast.xml' "$app_dir/script/stage_bundle.sh"
grep -q 'SUPublicEDKey' "$app_dir/script/stage_bundle.sh"
grep -q 'sparkle_ed_signature' "$app_dir/script/notarize.sh"
grep -q 'dmg_sha256' "$app_dir/script/notarize.sh"
grep -q 'application/x-apple-diskimage' ".github/workflows/macos-canary-release.yml"
grep -q 'SPARKLE_EDDSA_PRIVATE_KEY_BASE64' ".github/workflows/macos-canary-release.yml"
test -f "apps/mdx-host/src/routes/download/macos/appcast.xml/+server.js"
test -f "apps/mdx-host/src/routes/download/macos/update.zip/+server.js"
test -f "apps/mdx-host/src/routes/download/macos/installer.dmg/+server.js"
! grep -Eq '^[[:space:]]*codesign .*--deep' "$app_dir/script/stage_bundle.sh" "$app_dir/script/notarize.sh"
autoupdate_sign_line="$(grep -n 'SPARKLE_FRAMEWORK/Versions/Current/Autoupdate' "$app_dir/script/notarize.sh" | tail -1 | cut -d: -f1)"
app_sign_line="$(grep -n 'sign "\$MDX_SIGN_IDENTITY" "\$APP_BUNDLE"' "$app_dir/script/notarize.sh" | tail -1 | cut -d: -f1)"
[[ "$autoupdate_sign_line" -lt "$app_sign_line" ]]
grep -q 'WindowGroup("MDx"' "$app_dir/Sources/MDxOperator/App/MDxOperatorApp.swift"
grep -q 'http://127.0.0.1:18890' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/runtime-projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/repos/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/recipes.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/long-horizon-missions/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/fleet-plans/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/control-plane/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/build-requests/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/ship-decisions/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/source-host-readiness.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/pr-handoffs.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/browser-audits.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/machine-league/fleet-runs/arbitrations/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/learning/memory-activations/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/learning/adaptation-grants/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/memory/consolidation-ratifications/projection.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/forge/model-scorecard.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q '/learning/memory-supersedes.json' "$app_dir/Sources/MDxOperator/Services/MDxRouteClient.swift"
grep -q 'PRODUCT_NAME="MDxWorkbench"' "$app_dir/script/build_and_run.sh"
grep -q 'DISPLAY_NAME="MDx"' "$app_dir/script/build_and_run.sh"
grep -q 'BUNDLE_ID="com.mdx.app"' "$app_dir/script/build_and_run.sh"
grep -q 'MDX_API_URL' "$app_dir/script/build_and_run.sh"
grep -q -- '--env "MDX_API_URL=' "$app_dir/script/build_and_run.sh"
grep -q 'MDX_SHOT_TAB' "$app_dir/script/build_and_run.sh"
grep -q 'Start a build' "$app_dir/Sources/MDxOperator/Views/DetailView.swift"
grep -q 'GovernedActionKind' "$app_dir/Sources/MDxOperator/Models/OperatorModels.swift"
grep -q '/forge/build-requests.json' "$app_dir/Sources/MDxOperator/Models/OperatorModels.swift"
grep -q '/forge/pr-handoffs.json' "$app_dir/Sources/MDxOperator/Models/OperatorModels.swift"
grep -q 'script/package_release.sh' "$app_dir/Sources/MDxOperator/Views/DetailView.swift"
grep -q 'NavigationSplitView' "$app_dir/Sources/MDxOperator/Views/ContentView.swift"
grep -q 'inspector(isPresented:' "$app_dir/Sources/MDxOperator/Views/ContentView.swift"
grep -q 'enum AppRoute' "$app_dir/Sources/MDxOperator/Models/OperatorModels.swift"
grep -q 'case twin' "$app_dir/Sources/MDxOperator/Models/OperatorModels.swift"
grep -q 'case marketplace' "$app_dir/Sources/MDxOperator/Models/OperatorModels.swift"
grep -q 'case memory' "$app_dir/Sources/MDxOperator/Models/OperatorModels.swift"
grep -q 'TwinComposerCard' "$app_dir/Sources/MDxOperator/Views/DetailView.swift"
grep -q 'CommandPaletteView' "$app_dir/Sources/MDxOperator/Views/CommandPaletteView.swift"
grep -q 'NSViewRepresentable' "$app_dir/Sources/MDxOperator/Views/BrowserPreviewView.swift"
grep -q 'websiteDataStore = .nonPersistent' "$app_dir/Sources/MDxOperator/Views/BrowserPreviewView.swift"
grep -q 'compileContentRuleList' "$app_dir/Sources/MDxOperator/Views/BrowserPreviewView.swift"
grep -q 'startBrowserEvolution' "$app_dir/Sources/MDxOperator/Stores/OperatorStore.swift"
grep -q 'Shipping stays a human decision' "$app_dir/Sources/MDxOperator/Views/DetailView.swift"
grep -q 'Governed' "$app_dir/Sources/MDxOperator/Views/DetailView.swift"
grep -q './apps/mdx-operator-macos/script/build_and_run.sh' ".codex/environments/environment.toml"
grep -q 'provider: .apple' "$app_dir/Sources/MDxOperator/Services/CloudAuthStore.swift"
grep -q 'signInWithOAuth' "$app_dir/Sources/MDxOperator/Services/CloudAuthStore.swift"
grep -q 'Continue with Apple' "$app_dir/Sources/MDxOperator/Views/CloudGateView.swift"
! grep -q 'SignInWithAppleButton' "$app_dir/Sources/MDxOperator/Views/CloudGateView.swift"
! grep -q 'MDX_DEVELOPER_ID_PROFILE' "$app_dir/script/notarize.sh"
test ! -e "$app_dir/script/Entitlements.plist"
! grep -q -- '--entitlements' "$app_dir/script/notarize.sh"
! grep -q 'APPLE_DEVELOPER_ID_PROVISIONING_PROFILE_BASE64' ".github/workflows/macos-canary-release.yml"
grep -q 'apple_sign_in_transport -string "browser_oauth"' "$app_dir/script/notarize.sh"

(cd "$app_dir" && swift build --disable-sandbox)

# Mapper contract checks: pin JSON-to-model mapping against kernel projection
# fixtures so a wire-shape regression fails here, not as a blank surface.
(cd "$app_dir" && MDX_MAPPER_FIXTURES="$PWD/Tests/Fixtures" ./.build/debug/MDxWorkbench --mapper-checks)

# Xcode-backed XCTest proof. The parity suite defaults to an in-process HTTP
# fixture and only targets a live kernel when MDX_PARITY_BASE_URL is explicit.
(cd "$app_dir" && swift test --disable-sandbox)

echo "native_macos_operator_check: OK app=$app_dir xctest=deterministic"
