// Generated by scripts/forge-dogfood-marketing-proof.mjs from a sanitized live run.
export const forgeDogfoodProof = {
  "capturedAt": "2026-07-12T12:08:27.809Z",
  "ask": "Implement a policy bundle evaluator with explicit deny, review, and allow precedence, a stable decision trail, overlapping-rule tests, and safe default behavior.",
  "complexity": "hard",
  "geometry": "single",
  "runId": "forge_run_002408",
  "branch": "forge/run-forge_run_002408-mdx_ws_forge_run_002408_27820_7",
  "outcome": "Strict hard-gauntlet pass",
  "changedFiles": 2,
  "additions": 176,
  "deletions": 2,
  "checksPassed": 1,
  "checksFailed": 0,
  "checkCommands": [
    "npm test"
  ],
  "trail": [
    {
      "label": "Accepted scoped work",
      "detail": "Selected the Node proof contract and one isolated worker.",
      "receiptId": "forge_harness_run_receipt_002414"
    },
    {
      "label": "Planned the precedence model",
      "detail": "Made deny, review, and allow ordering plus the public entrypoint explicit before writing.",
      "receiptId": "forge_harness_run_receipt_003268"
    },
    {
      "label": "Turned the proof green",
      "detail": "The selected test command passed the canary, overlapping-rule, and default-behavior cases.",
      "receiptId": "forge_harness_run_receipt_003471"
    },
    {
      "label": "Returned a reviewable branch",
      "detail": "Finished after seven turns with two changed files and no generated artifacts.",
      "receiptId": "forge_harness_run_receipt_003878"
    }
  ],
  "humanBoundary": "Branch ready. A person still makes the ship call.",
  "sourceRoutes": [
    "/forge/runs/projection.json",
    "/forge/review-packet.json",
    "/forge/control-plane/projection.json"
  ]
};
